admin:
   build: ./admin
   ports:
       - "8000:4000"
   links:
       - redis
   volumes:
       - "./admin/web:/usr/src/admin"

web:
    build: ./app
    ports:
        - "8888:3000"
    links:
        - redis
    command: node index.js
    volumes:
        - "./app:/usr/src/app"

kue:
    build: ./task
    ports:
        - "5555:4000"
    links:
        - redis
    command: node index.js
    volumes:
        - "./task:/usr/src/task"


redis:
    image: redis
    ports:
        - "6379:6379"


nginx:
   restart: always
   build: ./nginx
   ports:
       - "80:80"
       - "0.0.0.0:8080:80"
   volumes_from:
       - web
   links:
       - web
